/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://maven.pkg.github.com/accel-hack/accel-parts")
    }
}

dependencies {
    api(libs.com.google.guava.guava)
    api(libs.com.accelhack.commons.utils)
    api(libs.com.accelhack.commons.model)
    api(libs.org.springframework.boot.spring.boot.starter.web)
    api(libs.org.springframework.boot.spring.boot.starter.validation)
    api(libs.org.springframework.boot.spring.boot.starter.security)
    api(libs.org.springframework.boot.spring.boot.starter.oauth2.client)
    api(libs.org.springframework.boot.spring.boot.starter.actuator)
    api(libs.com.auth0.java.jwt)
    api(libs.org.springframework.boot.spring.boot.configuration.processor)
    api(libs.org.mybatis.dynamic.sql.mybatis.dynamic.sql)
    api(libs.org.mybatis.spring.boot.mybatis.spring.boot.starter)
    api(libs.org.projectlombok.lombok)
    api(libs.org.springframework.security.spring.security.crypto)
    api(libs.org.apache.commons.commons.lang3)
    runtimeOnly(libs.mysql.mysql.connector.java)
    runtimeOnly(libs.org.springframework.boot.spring.boot.devtools)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.org.junit.jupiter.junit.jupiter)
    testImplementation(libs.org.mockito.mockito.inline)
    testImplementation(libs.com.github.springtestdbunit.spring.test.dbunit)
    testImplementation(libs.org.dbunit.dbunit)
    testImplementation(libs.org.powermock.powermock.reflect)
    testImplementation(libs.org.springframework.security.spring.security.test)
}

group = "com.accelhack.application.api"
version = "1.0-SNAPSHOT"
description = "ApiApplication"
java.sourceCompatibility = JavaVersion.VERSION_20

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
