USE SIMPLE_APPLICATION;

ALTER TABLE SIMPLE_APPLICATION.SUPER_USER
    ADD CONSTRAINT `FK01_SUPER_USER` FOREIGN KEY (`SUPER_USER_ID`) REFERENCES `USER` (`ID`);

ALTER TABLE SIMPLE_APPLICATION.SUPER_USER
    ADD CONSTRAINT `FK02_SUPER_USER` FOREIGN KEY (`TARGET_USER_ID`) REFERENCES `USER` (`ID`);

ALTER TABLE SIMPLE_APPLICATION.USER_ROLE
    ADD CONSTRAINT `FK01_USER_ROLE` FOREIGN KEY (`USER_ID`) REFERENCES `USER` (`ID`);

ALTER TABLE SIMPLE_APPLICATION.USER_ROLE
    ADD CONSTRAINT `FK02_USER_ROLE` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ID`);

ALTER TABLE SIMPLE_APPLICATION.ROLE_POLICY
    ADD CONSTRAINT `FK01_ROLE_POLICY` FOREIGN KEY (`ROLE_ID`) REFERENCES `ROLE` (`ID`);

ALTER TABLE SIMPLE_APPLICATION.ROLE_POLICY
    ADD CONSTRAINT `FK02_ROLE_POLICY` FOREIGN KEY (`POLICY_ID`) REFERENCES `POLICY` (`ID`);

USE YOUR_APPLICATION;