name: run-test

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:

  start:
    runs-on: ubuntu-latest
    steps:
      - run: echo "start test"

  code-validation:
    needs: [ start ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK (java20)
        uses: actions/setup-java@v3
        with:
          java-version: 20
          distribution: corretto

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

            # - name: Run Tests
            #   env:
            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #   run: ./mvnw -f pom.xml formatter:validate

  mock-tests:
    needs: [ start ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - "sample.domain.**"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK (java20)
        uses: actions/setup-java@v3
        with:
          java-version: 20
          distribution: corretto

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

            # - name: Run Tests
            #   env:
            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #   run: >
            #     ./mvnw -f pom.xml
            #     -Duser.timezone=UTC
            #     -Dtest="com.accelhack.spring.api.${{ matrix.test }}"
            #     -s settings.xml
            #     test


  spring-boot-tests:
    needs: [ start ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - "**"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build test database
        run: docker compose up test-db -d

      - name: Set up JDK (java20)
        uses: actions/setup-java@v3
        with:
          java-version: 20
          distribution: corretto

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

            # - name: Run Tests
            #   env:
            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            #   run: >
            #     ./mvnw -f pom.xml
            #     -Duser.timezone=UTC
            #     -Dtest="com.accelhack.spring.api.${{ matrix.test }}"
            #     -s settings.xml
            #     test
